excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://bridal-Party.github.io
title: Writing in the Heart of Dixie
tagline: yeah gonna write some shit 
description: just a small town boy lovin' and livin' the sweet country air of Dixie
paginate: 5